# You're given scores of 4 students across 3 subjects. Perform analysis using NumPy.

In [1]:
import numpy as np

In [2]:
# Rows = Students, Columns = Subjects
scores = np.array([
    [85, 90, 88],   # Student 1
    [78, 81, 85],   # Student 2
    [92, 88, 91],   # Student 3
    [70, 75, 80]    # Student 4
])


# Find:


In [12]:
# The shape of the array
arr = scores.shape

In [14]:
arr

(4, 3)

In [20]:
# Average score of each student
np.mean(scores,axis=1)

array([87.66666667, 81.33333333, 90.33333333, 75.        ])

In [22]:
#verage score in each subject
np.mean(scores,axis=0)

array([81.25, 83.5 , 86.  ])

In [27]:
# Highest score and its position
max_score = np.max(scores)
max_score

np.int64(92)

In [28]:
max_position = np.unravel_index(np.argmax(scores), scores.shape)
max_position

(np.int64(2), np.int64(0))

In [29]:
# Standard deviation of the scores
np.std(scores)

np.float64(6.575945221453381)

In [31]:
# Step 3: Add new student
new_student=[94,99,88]
scores = np.vstack([scores,new_student])
scores

array([[85, 90, 88],
       [78, 81, 85],
       [92, 88, 91],
       [70, 75, 80],
       [94, 99, 88]])

In [40]:
# Step 4: Remove lowest scoring subject (column)
lowest_subject_index = np.argmin(np.mean(scores, axis=0))


In [41]:
np.delete(scores, lowest_subject_index, axis=1)

array([[90, 88],
       [81, 85],
       [88, 91],
       [75, 80],
       [99, 88]])