# Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]],np.int64)

In [3]:
myarr[0,1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] =45

In [7]:
myarr

array([[ 3, 45, 37,  7]])

# Array creation : conversion from python structures

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,24})

array({24, 34}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng =np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10)

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp= np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56593696e-307, 1.60219035e-306, 1.42419938e-306],
       [7.56603881e-307, 8.45603440e-307, 3.56043054e-307,
        1.60219306e-306, 6.23059726e-307, 1.06811422e-306],
       [3.56043054e-307, 1.37961641e-306, 1.05695167e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        2.22523140e-306, 1.02360867e-306, 8.91253127e-313]])

In [22]:
emp_like =np.empty_like(lspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr =arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.shape

(3, 33)

In [33]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar.sum(axis=0)

array([12,  8,  9])

In [37]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [44]:
for item in ar.flat:
     print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

72

In [48]:
one = np.array([1,3,4,632,2])

In [50]:
one.argmax()

np.int64(3)

In [51]:
one.argmin()

np.int64(0)

In [52]:
one.argsort()

array([0, 4, 1, 2, 3])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argmin()

np.int64(8)

In [57]:
ar.argmax()

np.int64(6)

In [58]:
ar.argmax(axis=0)

array([2, 1, 1])

In [59]:
ar.argmax(axis=1)

array([2, 2, 0])

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [61]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2 =np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [66]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [68]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [69]:
ar *ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [70]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [71]:
ar.sum()

np.int64(29)

In [72]:
ar.max()

np.int64(7)

In [74]:
ar.min()

np.int64(0)

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [77]:
np.count_nonzero(ar)

8

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [79]:
ar[1,2]=0

In [80]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [81]:
import sys

In [84]:
py_ar =[0,4,55,2]

In [85]:
np_ar = np.array(py_ar)

In [88]:
sys.getsizeof(1) * len(py_ar)

112

In [89]:
np_ar.itemsize*np_ar.size

32